include $(SRC_RT)/myOS/kernel/mem/Makefile
include $(SRC_RT)/myOS/kernel/taskScheduler/Makefile

KERNEL_OBJS = output/myOS/kernel/wallClock.o \
		  output/myOS/kernel/task.o \
		  output/myOS/kernel/taskPara.o \
	      $(MEM_OBJS) \
		  $(TASK_SCHEDULER_OBJS)
