TASK_SCHEDULER_OBJS = output/myOS/kernel/taskScheduler/taskFCFS.o \
	      output/myOS/kernel/taskScheduler/taskPrio.o \
		  output/myOS/kernel/taskScheduler/taskSJF.o \
		  output/myOS/kernel/taskScheduler/taskRR.o 
